name: 'Master Push'
on:
  push:
    branches:
      - 'master'

jobs:

  cut-release:
    name: 'Cut Release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Install expect'
        run: sudo apt-get update && sudo apt-get install -y expect
      
      - name: 'Run Expect Script'
        run: expect scripts/soldeer_publish.sh ${{ vars.SOLDEER_EMAIL }} ${{ secrets.SOLDEER_PASSWORD }}

      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.head.sha }}
          fetch-depth: 0

      - name: 'Create release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          short_sha=$(git rev-parse --short ${{ github.sha }})
          gh release create ${short_sha} --target ${{ github.sha }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: 'Build'
        run: cargo install soldeer

      - name: 'Run tests'
