name: 'Master Push'
on:
  push:
    branches:
      - 'master'

jobs:

  cut-release:
    name: 'Cut Release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Install expect'
        run: sudo apt-get update && sudo apt-get install -y expect
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.2.0

      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Run Expect Script'
        shell: bash
        run: |
          pushd src > /dev/null
          script -q -c "expect scripts/soldeer_publish.expect ${{ vars.SOLDEER_EMAIL }} ${{ secrets.SOLDEER_PASSWORD }} ${{ github.event.push.head.sha }}" /dev/null
          popd > /dev/null

      - name: 'Create release'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          short_sha=$(git rev-parse --short ${{ github.sha }})
          gh release create ${short_sha} --target ${{ github.sha }}
